<?
   $PREFIX="/usr/local/mbm";

   $PATHS["bin"]=$PREFIX."/bin";
   $PATHS["etc"]=$PREFIX."/etc";
   $PATHS["web"]=$PREFIX."/web";
   $PATHS["pub"]=$PREFIX."/web/pub";
   $PATHS["priv"]=$PREFIX."/web/priv";
   $PATHS["tpl"]=$PREFIX."/web/priv/tpl";
   $PATHS["systpl"]=$PREFIX."/web/priv/systpl";
   $PATHS["lib"]=$PREFIX."/web/priv/lib";
   $PATHS["inc"]=$PREFIX."/web/priv/inc";
   $PATHS["procedures"]=$PREFIX."/web/priv/procedures";
   $PATHS["var"]=$PREFIX."/var";
   $PATHS["log"]=$PREFIX."/var/log";
   $PATHS["backup"]=$PREFIX."/var/backup";
   //$PATHS[""]="{}";

?>
